const types = {
    SUCCESS_LOADING_PRODUCT_DATA: 'SUCCESS_LOADING_PRODUCT_DATA',
    ERROR_LOADING_PRODUCT_DATA: 'ERROR_LOADING_PRODUCT_DATA',
    SUCCESS_CLOSING_MODAL: 'SUCCESS_CLOSING_MODAL'
}

export default types