const types = {
    SUCCESS_LOADING_PRODUCTS: 'SUCCESS_LOADING_PRODCTS',
    ERROR_LOADING_PRODUCTS: 'ERROR_LOADING_PRODUCTS',
    SUCCESS_LOADING_FEATURED_PRODUCT: 'SUCCESS_LOADING_FEATURED_PRODUCT',
    ERROR_LOADING_FEATURED_PRODUCT: 'ERROR_LOADING_FEATURED_PRODUCT'
}

export default types